#!/bin/bash

service::config_set() {
  config::check_or_set $@ $SERVICE_CONFIG
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi
}

check $@
