version: '3.7'

services:
  elasticsearch:
    restart: always
    image: elasticsearch:${SERVICE_ELASTIC_SEARCH_IMAGE_VERSION}
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    environment:
      discovery.type: single-node
    user: root # fix elasticsearch user permission denied
    volumes:
      - ${SERVICE_DATA}:/usr/share/elasticsearch/data
    mem_limit: 20480m
      
networks:
  default:
    external: true
    name: compose-ingress
