version: '3.7'

services:
  elasticsearch:
    restart: always
    image: whatwewant/elasticsearch:${SERVICE_ELASTIC_SEARCH_IMAGE_VERSION}
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    environment:
      discovery.type: single-node
      
networks:
  default:
    external: true
    name: compose-ingress
