version: '3.7'

services:
  elasticsearch:
    restart: always
    image: whatwewant/elasticsearch:${SERVICE_ELASTIC_SEARCH_IMAGE_VERSION}
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - ${SERVICE_DATA}:/usr/share/elasticsearch/data
    mem_limit: ${SERVICE_ELASTIC_SEARCH_RESOURCE_LIMIT_MEMORY}
    cpus: ${SERVICE_ELASTIC_SEARCH_RESOURCE_LIMIT_CPU}
      
networks:
  default:
    external: true
    name: compose-ingress
